## ------------------------------------------------------------------------ ##
##  .Brewfile                                Nicholas Berlette, 2022-06-07  ##
## ------------------------------------------------------------------------ ##
##   https://github.com/nberlette/codespace-dotfiles/blob/main/.Brewfile    ##
## ------------------------------------------------------------------------ ##
##              MIT © Nicholas Berlette <nick@berlette.com>                 ##
## ------------------------------------------------------------------------ ##

## auto-generated by the `brew bundle dump` command after installation

tap "homebrew/bundle"
tap "homebrew/core"

# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
brew "tmux"
